runtime: go113

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

env_variables:
  GREMLIN_TEAM_ID: "GREMLIN_TEAM_ID"
  GREMLIN_API_KEY: "GREMLIN_API_KEY"
